"""Build a governed, data-grounded DCF valuation memo deck for a real
public Investment Banking DCF instance.

Eighth domain on the IC-memo/pptx system, reusing
tools/builders/pptx_helpers.py unchanged, and the first to read an
agent-tool-drafted instance rather than a registered
standards/public_cases/index.json case: this deck consumes
01_Investment_Banking/instances/public_adobe_dcf_proxy.xlsx, generated by
tools/agents/dcf_comps.py --use-adobe-dcf-fixture. That instance's own
manifest schema is simpler than a public case's (no top-level
sources/outcome list, no per-input input_kind field -- see
docs/AGENT_TOOL_CONTRACT.md), so real-vs-illustrative labeling here reads
each input's own source name instead ("XBRL annual fact series" = real,
"Repo precedent" = modeler_assumption).

Every number on a slide is read from the instance workbook after a real
LibreOffice recalculation (tools.recalc). Nothing on any slide is invented
here -- this script only reads and renders. This deck ends in a DCF
output (implied value/share), not a forecast-vs-realized outcome check --
an agent-drafted valuation snapshot, tagged
classification: "agent_tool_draft" in its own manifest, is not a
registered public case with a tracked realized outcome.

Usage:
    python tools/builders/build_dcf_memo.py --instance-slug public_adobe_dcf_proxy
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "tools"))

import pptx_helpers as ph  # noqa: E402
from recalc import recalc  # noqa: E402

import openpyxl  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
DOMAIN = ROOT / "01_Investment_Banking"


def _load_manifest(instance_slug: str) -> dict[str, Any]:
    path = DOMAIN / "instances" / f"{instance_slug}.manifest.json"
    return json.loads(path.read_text(encoding="utf-8"))


def _recalculated_workbook(output_rel: str) -> openpyxl.Workbook:
    src = ROOT / output_rel
    with tempfile.TemporaryDirectory(dir=ROOT) as tmp:
        scratch = Path(tmp) / src.name
        shutil.copyfile(src, scratch)
        result = recalc(str(scratch), timeout=90)
        if result.get("status") != "success" or result.get("total_errors", 1):
            raise RuntimeError(f"recalculation did not succeed cleanly: {result}")
        return openpyxl.load_workbook(scratch, data_only=True)


def _fmt_usd_mm(value: float) -> str:
    return f"${value:,.1f}mm"


def _fmt_pct(value: float, decimals: int = 1) -> str:
    return f"{value * 100:.{decimals}f}%"


def build_dcf_memo(instance_slug: str, output: Path) -> None:
    manifest = _load_manifest(instance_slug)
    real_inputs = [i for i in manifest["inputs"] if "XBRL" in i["source"]["name"]]
    precedent_inputs = [i for i in manifest["inputs"] if "precedent" in i["source"]["name"].lower()]
    real_source = real_inputs[0]["source"] if real_inputs else None

    wb = _recalculated_workbook(manifest["output"])
    dcf = wb["DCF"]
    is_sheet = wb["IS"]

    company_name = manifest["cover"]["Title:"].split(" -- ")[0]
    as_of = manifest["as_of"]

    base_revenue = is_sheet["E5"].value
    fy1_revenue = is_sheet["F5"].value
    wacc = dcf["I5"].value
    terminal_growth = dcf["I6"].value
    enterprise_value = dcf["I10"].value
    equity_value = dcf["I12"].value
    implied_value_per_share = dcf["I14"].value
    net_debt = dcf["I11"].value
    diluted_shares = dcf["I13"].value

    prs = ph.new_presentation()

    # 1. Title
    ph.add_title_slide(
        prs,
        f"{company_name} — DCF Valuation (Agent-Drafted)",
        "Real, disclosed operating base and cost structure; WACC and terminal growth are "
        "modeler_assumption at this repo's own established precedent — no issuer discloses either.",
        f"As of {as_of}  ·  classification: agent_tool_draft  ·  Not a client deliverable — "
        "not counted toward M4 evidence, human review pending (Issue #7)",
    )

    # 2. Provenance
    slide = ph.add_content_slide(prs, "Reading this deck", kicker="Provenance")
    ph.add_bullets(
        slide, ph.MARGIN, ph.Inches(1.5), ph.SLIDE_W - 2 * ph.MARGIN, ph.Inches(2.8),
        [
            f"Real, disclosed: base-year (FY0A) revenue, revenue growth, gross margin, opex %, "
            f"effective tax rate, D&A-to-capex ratio, capex %, diluted shares, and net debt are all "
            f"computed from {real_source['name'] if real_source else 'XBRL'} — the same already-fetched "
            "source software-public-adobe-fy2025 uses, no new fetch.",
            f"modeler_assumption, explicitly attributed: WACC ({_fmt_pct(wacc, 0)}) and terminal growth "
            f"({_fmt_pct(terminal_growth, 1)}) — no issuer ever discloses either — reuse this repo's own "
            "prior assumption for a large-cap tech valuation (ib-public-microsoft-linkedin-2016) rather "
            "than an unsourced fresh guess.",
            "Not sourced: Comps peer data (ticker, price, market cap, EV/Revenue for comparable "
            "companies) — a real, stated gap requiring a fresh multi-company market-data pull this pass "
            "did not attempt.",
            "Generated by an L3 agent tool (tools/agents/dcf_comps.py), not yet human-reviewed — this is "
            "an illustrative snapshot of the governed pipeline, not a client-ready valuation.",
        ],
        size=14.5,
    )
    ph.add_footer(slide, f"classification: agent_tool_draft  ·  {instance_slug}.manifest.json")

    # 3. Operating base (real)
    slide = ph.add_content_slide(prs, "Operating base", kicker="Real, XBRL-sourced")
    growth_pct = fy1_revenue / base_revenue - 1 if base_revenue else 0
    ph.add_stat_row(
        slide, ph.Inches(1.5),
        [
            ph.Stat(_fmt_usd_mm(base_revenue), "FY0A revenue (base)", tag="XBRL", color=ph.NAVY),
            ph.Stat(_fmt_usd_mm(fy1_revenue), "FY1E revenue (projected)", tag="Computed", color=ph.NAVY),
            ph.Stat(_fmt_pct(growth_pct, 1), "FY1 growth applied", tag="XBRL, derived", color=ph.NAVY),
        ],
    )
    ph.add_table(
        slide, ph.MARGIN, ph.Inches(3.6), ph.SLIDE_W - 2 * ph.MARGIN, ph.Inches(2.6),
        ["Real input", "Value", "Source"],
        [
            [item["cell"], f"{item['value']:,g}", "XBRL"]
            for item in real_inputs
            if item["sheet"] in ("Assumptions", "IS")
        ][:8],
        col_widths=[1.2, 1.5, 5],
    )
    ph.add_footer(slide, f"Source: {real_source['name'] if real_source else 'n/a'} — {real_source['url'] if real_source else ''}")

    # 4. Discount and terminal assumptions (modeler_assumption)
    slide = ph.add_content_slide(prs, "Discount rate and terminal growth", kicker="modeler_assumption — explicitly attributed")
    ph.add_stat_row(
        slide, ph.Inches(1.6),
        [
            ph.Stat(_fmt_pct(wacc, 0), "WACC", tag="Repo precedent", color=ph.ILLUSTRATIVE_TAG),
            ph.Stat(_fmt_pct(terminal_growth, 1), "Terminal growth", tag="Repo precedent", color=ph.ILLUSTRATIVE_TAG),
        ],
    )
    ph.add_text(
        slide, ph.MARGIN, ph.Inches(3.2), ph.SLIDE_W - 2 * ph.MARGIN, ph.Inches(1.6),
        "No issuer ever discloses its own WACC or terminal growth rate as a matter of GAAP or SEC "
        "reporting — these are irreducibly modeler judgment. Rather than choose a fresh, unattributed "
        "number, this case reuses this repo's own prior large-cap-tech precedent "
        "(ib-public-microsoft-linkedin-2016) verbatim.",
        size=14, color=ph.CHARCOAL,
    )
    ph.add_disclosure_note(
        slide,
        f"Assumptions!C13/C14 (labeled 'WACC %'/'Terminal growth %') exist on the template but no formula "
        f"reads them — confirmed by grep, not assumed. These values are written directly to DCF!I5/I6, "
        "the cells the discount-factor and terminal-value formulas actually reference.",
    )

    # 5. DCF output — decision
    slide = ph.add_content_slide(prs, "Implied valuation", kicker="Decision — agent-drafted, not client-ready")
    ph.add_stat_row(
        slide, ph.Inches(1.6),
        [
            ph.Stat(_fmt_usd_mm(enterprise_value), "Enterprise value", tag="Computed", color=ph.NAVY),
            ph.Stat(_fmt_usd_mm(equity_value), "Equity value", tag="Computed", color=ph.NAVY),
            ph.Stat(f"${implied_value_per_share:,.2f}", "Implied value/share", tag="Computed",
                    color=ph.POSITIVE if implied_value_per_share > 0 else ph.NEGATIVE),
        ],
    )
    ph.add_bullets(
        slide, ph.MARGIN, ph.Inches(3.4), ph.SLIDE_W - 2 * ph.MARGIN, ph.Inches(2.4),
        [
            f"Net debt of {_fmt_usd_mm(net_debt)} and {diluted_shares:,.1f}mm diluted shares are both "
            "real, XBRL-computed facts feeding the equity bridge and per-share conversion.",
            "This valuation has no Comps cross-check yet — a peer multiple sanity check on the DCF "
            "output is a real, stated gap, not performed in this pass.",
            "classification: agent_tool_draft, counts_toward_M4: false — this instance cannot be "
            "presented as a client deliverable or counted as reviewed evidence ahead of human sign-off "
            "(Issue #7), regardless of how real the underlying inputs are.",
        ],
        size=15,
    )
    ph.add_footer(
        slide,
        f"Model: 01_Investment_Banking/_template_BASE.xlsx  ·  Instance: {manifest['output']}  ·  "
        "classification: agent_tool_draft",
    )

    ph.save(prs, output)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--instance-slug", default="public_adobe_dcf_proxy")
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()
    output = args.output or DOMAIN / "presentations" / f"{args.instance_slug}-dcf-memo.pptx"
    build_dcf_memo(args.instance_slug, output)
    print(f"saved {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
